python3 ../../../src/summarize.py ../3_subject_object_split.txt | sort -u > summaries.txt

#Run the pubtator scripts
cd pubtator
bash BUILD
cd ..

cd directionality
bash BUILD
cd ..
cd directionality_abstracts
bash BUILD
cd ..
cd no_dgidb
bash BUILD
cd ..
cd directionality_abstracts_nodgidb
bash BUILD
cd ..
cd timecapsule
bash BUILD
cd ..

