cp ../mappings/entrez/human_genes.txt .
cp ../ground_truth/pubmed/dates/pmid_to_date.txt .
cp ../no_text_mining/reactome_entrez.txt .
cp ../mappings/mesh/mesh_to_registry_id.txt .
cp ../mappings/pubchem/filtered_id_maps.txt .
cp ../ground_truth/dgidb/mod_to_entrez.txt .
cp ../ground_truth/dgidb/dgidb_pmids.txt .
cp ../mappings/hgnc/hgnc_to_entrez.txt .

cp ../pmc/gene/4_parmesan/directionality_abstracts/directionality.txt parmesan_gene_directionality.txt
cp ../pmc/drug/4_parmesan/directionality_abstracts/directionality.txt parmesan_drug_directionality.txt

cp ../pmc/gene/4_parmesan/directionality_abstracts/consensus_directionality.txt parmesan_gene_consensus_directionality.txt
cp ../pmc/drug/4_parmesan/directionality_abstracts/consensus_directionality.txt parmesan_drug_consensus_directionality.txt

cp -r ../pmc/gene/6_hypotheses_with_pubmed/timecapsule/pergene gene_timecapsule_hypotheses
cp ../pmc/gene/4_parmesan/directionality_abstracts/accuracy_test/power_samplesize.txt gene_power.txt

cp -r ../pmc/drug/6_hypotheses_with_pubmed/timecapsule/pergene drug_timecapsule_hypotheses

mkdir minscore_to_no_genes
cp ../abstracts/drugs/5_hypotheses/no_dgidb/minscore_to_no_genes.txt minscore_to_no_genes/pubmed_drug.txt
cp ../pmc/drug/5_hypotheses/no_dgidb/minscore_to_no_genes.txt minscore_to_no_genes/pmc_drug.txt
cp ../pmc/drug/6_hypotheses_with_pubmed/no_dgidb/minscore_to_no_genes.txt minscore_to_no_genes/pmc_pubmed_drug.txt
cp ../abstracts/genes/5_hypotheses/hypotheses/minscore_to_no_genes.txt minscore_to_no_genes/pubmed_gene.txt
cp ../pmc/gene/5_hypotheses/hypotheses/minscore_to_no_genes.txt minscore_to_no_genes/pmc_gene.txt
cp ../pmc/gene/6_hypotheses_with_pubmed/hypotheses/minscore_to_no_genes.txt minscore_to_no_genes/pmc_pubmed_gene.txt

mkdir raw_comparison
cp ../abstracts/drugs/5_hypotheses/no_dgidb/raw_dgidb_comparison.txt raw_comparison/pubmed_drug.txt
cp ../pmc/drug/5_hypotheses/no_dgidb/raw_dgidb_comparison.txt raw_comparison/pmc_drug.txt
cp ../pmc/drug/6_hypotheses_with_pubmed/no_dgidb/raw_dgidb_comparison.txt raw_comparison/pmc_pubmed_drug.txt
cp ../abstracts/genes/5_hypotheses/hypotheses/raw_reactome_comparison.txt raw_comparison/pubmed_gene.txt
cp ../pmc/gene/5_hypotheses/hypotheses/raw_reactome_comparison.txt raw_comparison/pmc_gene.txt
cp ../pmc/gene/6_hypotheses_with_pubmed/hypotheses/raw_reactome_comparison.txt raw_comparison/pmc_pubmed_gene.txt


