cp ../mappings/entrez/human_genes.txt .
cp ../ground_truth/pubmed/dates/pmid_to_date.txt .
cp ../no_text_mining/reactome_entrez.txt .
cp ../mappings/mesh/mesh_to_registry_id.txt .
cp ../mappings/pubchem/filtered_id_maps.txt .
cp ../ground_truth/dgidb/mod_to_entrez.txt .
cp ../ground_truth/dgidb/dgidb_pmids.txt .
cp ../mappings/hgnc/hgnc_to_entrez.txt .

cp ../pmc/gene/4_parmesan/directionality_abstracts/directionality.txt parmesan_gene_directionality.txt
cp ../pmc/drug/4_parmesan/directionality_abstracts/directionality.txt parmesan_drug_directionality.txt

cp ../pmc/gene/4_parmesan/directionality_abstracts/consensus_directionality.txt parmesan_gene_consensus_directionality.txt
cp ../pmc/drug/4_parmesan/directionality_abstracts/consensus_directionality.txt parmesan_drug_consensus_directionality.txt

cp -r ../pmc/gene/6_hypotheses_with_pubmed/timecapsule/pergene gene_timecapsule_hypotheses
cp ../pmc/gene/4_parmesan/directionality_abstracts/accuracy_test/power_samplesize.txt gene_power.txt

cp -r ../pmc/drug/6_hypotheses_with_pubmed/timecapsule/pergene drug_timecapsule_hypotheses


