wget ftp://ftp.ncbi.nih.gov/gene/DATA/gene2ensembl.gz
wget ftp://ftp.ncbi.nih.gov/gene/DATA/gene2pubmed.gz
wget ftp://ftp.ncbi.nih.gov/gene/DATA/gene2accession.gz
wget ftp://ftp.ncbi.nih.gov/gene/DATA/gene_info.gz

