wget https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/CURRENT-Full/XML/Compound_000000001_000500000.xml.gz
wget https://ftp.ncbi.nlm.nih.gov/pubchem/Substance/CURRENT-Full/XML/Substance_000000001_000500000.xml.gz
wget https://ftp.ncbi.nlm.nih.gov/pubchem/RDF/reference/pc_reference2meshheading_000001.ttl.gz

wget https://ftp.ncbi.nlm.nih.gov/pubchem/Substance/CURRENT-Full/SDF/Substance_000000001_000500000.sdf.gz
wget https://ftp.ncbi.nlm.nih.gov/pubchem/Substance/CURRENT-Full/ASN/Substance_000000001_000500000.asn.gz

