modifier=$1
target=$2
BASEDIR=$(dirname "$0")

cat $BASEDIR/../4_parmesan/directionality_abstracts/ortholog_mapping.txt | awk 'BEGIN {FS = "\t"} $3 != 0 {if($5 == ".") {cmod = $1} else {cmod = $5} if($8 == "."){ctarg = $2} else{ctarg = $8} print cmod "\t" ctarg "\t" $3 "_" $1 "_" $2 "\t" $0}' | awk '$1 == "'$modifier'"' | sort -k2,2 | join -t$'\t' -1 2 -2 1 - <(cat $BASEDIR/../4_parmesan/directionality_abstracts/ortholog_mapping.txt | awk 'BEGIN {FS = "\t"} $3 != 0 {if($5 == ".") {cmod = $1} else {cmod = $5} if($8 == "."){ctarg = $2} else{ctarg = $8} print cmod "\t" ctarg "\t" $3 "_" $1 "_" $2 "\t" $0}' | awk '$2 == "'$target'"' | sort -k1,1) | sort -k3,3 | join -t$'\t' -1 3 -2 1 - <(cat $BASEDIR/../4_parmesan/summaries_with_entrez.txt $BASEDIR/../../../abstracts/genes/4_parmesan/summaries_with_entrez.txt | awk 'BEGIN {FS = "\t"} {print $1 "_" $8 "_" $9 "\t" $0}' | sort -k1,1) | cut -f2- | sort -t$'\t' -k14,14 | join -t$'\t' -1 14 -2 1 - <(cat $BASEDIR/../4_parmesan/summaries_with_entrez.txt $BASEDIR/../../../abstracts/genes/4_parmesan/summaries_with_entrez.txt | awk 'BEGIN {FS = "\t"} {print $1 "_" $8 "_" $9 "\t" $0}' | sort -k1,1) | cut -f2- | awk 'BEGIN {FS = "\t"} {print $1 "\t" $5 "\t" $3 "\t" $8 "\t" $9 "\t" $4 "\t" $11 "\t" $12 "\t" $16 "\t" $14 "\t" $19 "\t" $20 "\t" $15 "\t" $22 "\t" $23 "\t" $29 " " $25 " " $26 " " $28 "; " $38 " " $34 " " $35 " " $37}' | sed 's/\t\. /\t/g' | sed 's/; \. /; /g' | sort -k1,1 | join -t$'\t' <(cat $BASEDIR/../4_parmesan/directionality_abstracts/consensus_directionality.txt | awk '$2 == "'$target'"' | cut -f1,3 | sort -k1,1) - | sort -k1,1 | join -t$'\t' <(cat $BASEDIR/../4_parmesan/directionality_abstracts/consensus_directionality.txt | awk '$1 == "'$modifier'"' | cut -f2,3 | sort -k1,1) - | sort -u


#cat ../../4_parmesan/directionality_abstracts/ortholog_mapping.txt | awk 'BEGIN {FS = "\t"} $3 != 0 {if($5 == ".") {cmod = $1} else {cmod = $5} if($8 == "."){ctarg = $2} else{ctarg = $8} print cmod "\t" ctarg "\t" $3 "_" $1 "_" $2 "\t" $0}' | awk '$1 == "'$modifier'"' | sort -k2,2 | join -t$'\t' -1 2 -2 1 - <(cat ../../4_parmesan/directionality_abstracts/ortholog_mapping.txt | awk 'BEGIN {FS = "\t"} $3 != 0 {if($5 == ".") {cmod = $1} else {cmod = $5} if($8 == "."){ctarg = $2} else{ctarg = $8} print cmod "\t" ctarg "\t" $3 "_" $1 "_" $2 "\t" $0}' | awk '$2 == "'$target'"' | sort -k1,1) | sort -k3,3 | join -t$'\t' -1 3 -2 1 - <(cat ../../4_parmesan/summaries_with_entrez.txt ../../../../abstracts/genes/4_parmesan/summaries_with_entrez.txt | awk 'BEGIN {FS = "\t"} {print $1 "_" $8 "_" $9 "\t" $0}' | sort -k1,1) | cut -f2- | sort -t$'\t' -k14,14 | join -t$'\t' -1 14 -2 1 - <(cat ../../4_parmesan/summaries_with_entrez.txt ../../../../abstracts/genes/4_parmesan/summaries_with_entrez.txt | awk 'BEGIN {FS = "\t"} {print $1 "_" $8 "_" $9 "\t" $0}' | sort -k1,1) | cut -f2- | awk 'BEGIN {FS = "\t"} {print $1 "\t" $5 "\t" $3 "\t" $8 "\t" $9 "\t" $4 "\t" $11 "\t" $12 "\t" $16 "\t" $14 "\t" $19 "\t" $20 "\t" $15 "\t" $22 "\t" $23 "\t" $29 " " $25 " " $26 " " $28 "; " $38 " " $34 " " $35 " " $37}' | sed 's/\t\. /\t/g' | sed 's/; \. /; /g' | sort -k1,1 | join -t$'\t' <(cat ../../4_parmesan/directionality_abstracts/consensus_directionality.txt | awk '$2 == "'$target'"' | cut -f1,3 | sort -k1,1) - | sort -k1,1 | join -t$'\t' <(cat ../../4_parmesan/directionality_abstracts/consensus_directionality.txt | awk '$1 == "'$modifier'"' | cut -f2,3 | sort -k1,1) - | sort -u

#cat ../../4_parmesan/directionality_abstracts/ortholog_mapping.txt | awk 'BEGIN {FS = "\t"} $3 != 0 {if($5 == ".") {cmod = $1} else {cmod = $5} if($8 == "."){ctarg = $2} else{ctarg = $8} print cmod "\t" ctarg "\t" $3 "_" $1 "_" $2 "\t" $0}' | awk '$1 == "'$modifier'"' | sort -k2,2 | join -t$'\t' -1 2 -2 1 - <(cat ../../4_parmesan/directionality_abstracts/ortholog_mapping.txt | awk 'BEGIN {FS = "\t"} $3 != 0 {if($5 == ".") {cmod = $1} else {cmod = $5} if($8 == "."){ctarg = $2} else{ctarg = $8} print cmod "\t" ctarg "\t" $3 "_" $1 "_" $2 "\t" $0}' | awk '$2 == "'$target'"' | sort -k1,1) | sort -k3,3 | join -t$'\t' -1 3 -2 1 - <(cat ../../4_parmesan/summaries_with_entrez.txt ../../../../abstracts/genes/4_parmesan/summaries_with_entrez.txt | awk 'BEGIN {FS = "\t"} {print $1 "_" $8 "_" $9 "\t" $0}' | sort -k1,1) | cut -f2- | sort -t$'\t' -k14,14 | join -t$'\t' -1 14 -2 1 - <(cat ../../4_parmesan/summaries_with_entrez.txt ../../../../abstracts/genes/4_parmesan/summaries_with_entrez.txt | awk 'BEGIN {FS = "\t"} {print $1 "_" $8 "_" $9 "\t" $0}' | sort -k1,1) | cut -f2- | awk 'BEGIN {FS = "\t"} {print $1 "\t" $5 "\t" $3 "\t" $8 "\t" $9 "\t" $4 "\t" $11 "\t" $12 "\t" $16 "\t" $14 "\t" $19 "\t" $20 "\t" $15 "\t" $22 "\t" $23 "\t" $29 " " $25 " " $26 " " $28 "; " $38 " " $34 " " $35 " " $37}' | sed 's/\t\. /\t/g' | sed 's/; \. /; /g' | sort -u

